service: nodetemplate

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x 
  memorySize: 2048
  stage: dev
  timeout: 15
  # region: ap-south-1 # Uncomment if you want to specify a region

functions:
  hello:
    handler: server.appServer
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
