service: magsonapi

frameworkVersion: "3"

provider:
  name: aws
  memorySize: 2048
  stage: dev
  timeout: 15
  runtime: nodejs18.x
  # region: ap-south-1 #to comment

functions:
  hello:
    handler: server.appServer
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
